name: Spell Check

on:
  pull_request:
    branches: [main]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cspell
        run: npm install -g cspell @cspell/dict-scientific-terms-us

      - name: Run cspell
        run: |
          cspell --config cspell.json \
            "README.md" "CITATION.cff" \
            "docs/**/*" \
            "src/ifes_apt_tc_data_modeling/**/*.py" \
            "tests/**/*.py"

      - name: Report success
        if: success()
        run: echo "No spelling errors found."